imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

#
#parameters:
#    database_name: test_mode


doctrine:
    dbal:
        driver: pdo_sqlite
#        memory: true
        path: '%kernel.project_dir%/var/data/data.sqlite'



web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true
